// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: cv2x_client_destined_msg.proto

package decoder

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  int32 `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv2x_client_destined_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_cv2x_client_destined_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_cv2x_client_destined_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ClientDestinedMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	MsgBytes []byte    `protobuf:"bytes,2,opt,name=MsgBytes,proto3" json:"MsgBytes,omitempty"`
}

func (x *ClientDestinedMsg) Reset() {
	*x = ClientDestinedMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv2x_client_destined_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDestinedMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDestinedMsg) ProtoMessage() {}

func (x *ClientDestinedMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cv2x_client_destined_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDestinedMsg.ProtoReflect.Descriptor instead.
func (*ClientDestinedMsg) Descriptor() ([]byte, []int) {
	return file_cv2x_client_destined_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDestinedMsg) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ClientDestinedMsg) GetMsgBytes() []byte {
	if x != nil {
		return x.MsgBytes
	}
	return nil
}

var File_cv2x_client_destined_msg_proto protoreflect.FileDescriptor

var file_cv2x_client_destined_msg_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x76, 0x32, 0x78, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x08, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22,
	0x5e, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x65,
	0x64, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cv2x_client_destined_msg_proto_rawDescOnce sync.Once
	file_cv2x_client_destined_msg_proto_rawDescData = file_cv2x_client_destined_msg_proto_rawDesc
)

func file_cv2x_client_destined_msg_proto_rawDescGZIP() []byte {
	file_cv2x_client_destined_msg_proto_rawDescOnce.Do(func() {
		file_cv2x_client_destined_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_cv2x_client_destined_msg_proto_rawDescData)
	})
	return file_cv2x_client_destined_msg_proto_rawDescData
}

var file_cv2x_client_destined_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cv2x_client_destined_msg_proto_goTypes = []interface{}{
	(*Position)(nil),          // 0: decoder.Position
	(*ClientDestinedMsg)(nil), // 1: decoder.ClientDestinedMsg
}
var file_cv2x_client_destined_msg_proto_depIdxs = []int32{
	0, // 0: decoder.ClientDestinedMsg.position:type_name -> decoder.Position
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cv2x_client_destined_msg_proto_init() }
func file_cv2x_client_destined_msg_proto_init() {
	if File_cv2x_client_destined_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cv2x_client_destined_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv2x_client_destined_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDestinedMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cv2x_client_destined_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cv2x_client_destined_msg_proto_goTypes,
		DependencyIndexes: file_cv2x_client_destined_msg_proto_depIdxs,
		MessageInfos:      file_cv2x_client_destined_msg_proto_msgTypes,
	}.Build()
	File_cv2x_client_destined_msg_proto = out.File
	file_cv2x_client_destined_msg_proto_rawDesc = nil
	file_cv2x_client_destined_msg_proto_goTypes = nil
	file_cv2x_client_destined_msg_proto_depIdxs = nil
}
