version: "3.3"

services:
  decode-agent-bridge:
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - mqtt
    depends_on:
      - decode-agent-playback
      - mosquitto
    command: -loglevel=0 
    volumes:
      - type: bind
        source: ./config/stream
        target: /etc/decode-agent
    ports:
      - "8080:8080"

  decode-agent-playback:
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - mqtt
    depends_on:
      - mosquitto
    command: -loglevel=0 
    volumes:
      - type: bind
        source: ./config/playback
        target: /etc/decode-agent

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
      - mqtt
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"

networks:
  mqtt: