subscribe:
publish:
  clientid: playback-pub
  server: mosquitto:1883
  topic: pubtest
op: 
  mode: playback
  playbackconfig: 
    file: /etc/decode-agent/bsm-sample.log
    loop: true
    pubfreq: 4000