apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-conf
data:
  mosquitto.conf: |-
    pid_file /var/run/mosquitto.pid
    log_dest file /mosquitto/log/mosquitto.log
    log_type all 

    # internal mqtt connections
    listener 1883
    protocol mqtt

    # external mqtt connection over websocket
    listener 8080
    protocol websockets