apiVersion: v1
kind: Service
metadata:
  name: decode-agent-external
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30901
  selector:
    app: decode-agent
