name: decodeAgent 
subscribe:
  server: mosquitto:1883
  topic: pubtest
  qos: 0
publish:
  server: mosquitto:1883
  topic: streamtest
  qos: 0 
op: 
  mode: stream
  format: json
  http-auth: /etc/decode-agent/http-auth
---
name: playbackAgent
subscribe:
publish:
  clientid: playback-pub
  server: mosquitto:1883
  topic: pubtest
op: 
  mode: playback
  playbackconfig: 
    file: /etc/decode-agent/bsm-sample.log
    loop: true
    pubfreq: 4000
    
