apiVersion: v1
kind: Service
metadata:
  name: mosquitto-external
spec:
  type: NodePort
  ports:
    - name: websocket
      port: 8080
      targetPort: 8080
      nodePort: 30900
  selector:
    app: mosquitto-broker